using System.Data; using MediDesk.Business.Interfaces; using MediDesk.Common.Contracts.Catalog; using MediDesk.Common.Contracts.Partners; using Microsoft.Data.SqlClient;
namespace MediDesk.Data.Repositories;
public sealed class CustomerRepository(SqlConnectionFactory f):ICustomerRepository {
 const string C="Id,FullName,Phone,Email,Address,City,State,CreditLimit,CreditBalance,IsActive,COALESCE(UpdatedAtUtc,CreatedAtUtc),RowVersion";
 public async Task<PagedResponse<CustomerDto>> GetPageAsync(CustomerQuery q,CancellationToken ct){var w="IsDeleted=0 AND (@Status IS NULL OR IsActive=CASE WHEN @Status='Active' THEN 1 ELSE 0 END) AND (@Search IS NULL OR FullName LIKE @Like OR Phone LIKE @Like OR Email LIKE @Like)"; var sql=$"SELECT COUNT(1) FROM dbo.Customers WHERE {w}; SELECT {C} FROM dbo.Customers WHERE {w} ORDER BY FullName OFFSET @Off ROWS FETCH NEXT @Size ROWS ONLY;"; await using var c=f.Create(); await c.OpenAsync(ct); await using var cmd=new SqlCommand(sql,c); P(cmd,q); await using var r=await cmd.ExecuteReaderAsync(ct); await r.ReadAsync(ct); var total=r.GetInt32(0); await r.NextResultAsync(ct); var rows=new List<CustomerDto>(); while(await r.ReadAsync(ct)) rows.Add(Read(r)); return new PagedResponse<CustomerDto>(rows,q.Page,q.PageSize,total);}
 public async Task<CustomerDto?> GetByIdAsync(long id,CancellationToken ct){await using var c=f.Create(); await c.OpenAsync(ct); await using var cmd=new SqlCommand($"SELECT {C} FROM dbo.Customers WHERE Id=@Id AND IsDeleted=0",c); cmd.Parameters.Add("@Id",SqlDbType.BigInt).Value=id; await using var r=await cmd.ExecuteReaderAsync(ct); return await r.ReadAsync(ct)?Read(r):null;}
 public async Task<CustomerDto> CreateAsync(CreateCustomerRequest x,long u,CancellationToken ct){const string s="INSERT dbo.Customers(FullName,Phone,Email,Address,City,State,CreditLimit,CreatedByUserId) OUTPUT INSERTED.Id VALUES(@N,@P,@E,@A,@C,@S,@L,@U)"; await using var c=f.Create(); await c.OpenAsync(ct); await using var cmd=new SqlCommand(s,c); Add(cmd,x,u); try{return (await GetByIdAsync(Convert.ToInt64(await cmd.ExecuteScalarAsync(ct)),ct))!;}catch(SqlException e) when(e.Number is 2601 or 2627){throw new InvalidOperationException("An active customer with this phone already exists.",e);}}
 public async Task<CustomerWriteResult> UpdateAsync(long id,UpdateCustomerRequest x,long u,CancellationToken ct){await using var c=f.Create(); await c.OpenAsync(ct); await using var cmd=new SqlCommand("UPDATE dbo.Customers SET FullName=@N,Phone=@P,Email=@E,Address=@A,City=@C,State=@S,CreditLimit=@L,IsActive=@Active,UpdatedByUserId=@U,UpdatedAtUtc=SYSUTCDATETIME() WHERE Id=@Id AND IsDeleted=0 AND RowVersion=@V",c); Add(cmd,x,u); cmd.Parameters.Add("@Active",SqlDbType.Bit).Value=x.IsActive; cmd.Parameters.Add("@Id",SqlDbType.BigInt).Value=id; cmd.Parameters.Add("@V",SqlDbType.Timestamp).Value=Convert.FromBase64String(x.RowVersion); try{if(await cmd.ExecuteNonQueryAsync(ct)>0)return new(true);}catch(SqlException e) when(e.Number is 2601 or 2627){throw new InvalidOperationException("An active customer with this phone already exists.",e);} await using var e2=new SqlCommand("SELECT COUNT(1) FROM dbo.Customers WHERE Id=@Id AND IsDeleted=0",c); e2.Parameters.Add("@Id",SqlDbType.BigInt).Value=id; return Convert.ToInt32(await e2.ExecuteScalarAsync(ct))>0?new(false,Conflict:true):new(false,NotFound:true);}
 public async Task<bool> SoftDeleteAsync(long id,long u,CancellationToken ct){await using var c=f.Create(); await c.OpenAsync(ct); await using var cmd=new SqlCommand("UPDATE dbo.Customers SET IsDeleted=1,UpdatedByUserId=@U,UpdatedAtUtc=SYSUTCDATETIME() WHERE Id=@Id AND IsDeleted=0 AND CreditBalance=0",c); cmd.Parameters.Add("@Id",SqlDbType.BigInt).Value=id; cmd.Parameters.Add("@U",SqlDbType.BigInt).Value=u; return await cmd.ExecuteNonQueryAsync(ct)>0;}
 static void P(SqlCommand c,CustomerQuery q){c.Parameters.Add("@Status",SqlDbType.NVarChar,10).Value=(object?)q.Status??DBNull.Value;c.Parameters.Add("@Search",SqlDbType.NVarChar,160).Value=(object?)q.Search??DBNull.Value;c.Parameters.Add("@Like",SqlDbType.NVarChar,170).Value=q.Search is null?DBNull.Value:$"%{q.Search}%";c.Parameters.Add("@Off",SqlDbType.Int).Value=(q.Page-1)*q.PageSize;c.Parameters.Add("@Size",SqlDbType.Int).Value=q.PageSize;}
 static void Add(SqlCommand c,CreateCustomerRequest x,long u){c.Parameters.Add("@N",SqlDbType.NVarChar,160).Value=x.FullName;c.Parameters.Add("@P",SqlDbType.NVarChar,18).Value=x.Phone;c.Parameters.Add("@E",SqlDbType.NVarChar,256).Value=(object?)x.Email??DBNull.Value;c.Parameters.Add("@A",SqlDbType.NVarChar,300).Value=(object?)x.Address??DBNull.Value;c.Parameters.Add("@C",SqlDbType.NVarChar,100).Value=(object?)x.City??DBNull.Value;c.Parameters.Add("@S",SqlDbType.NVarChar,100).Value=(object?)x.State??DBNull.Value;c.Parameters.Add("@L",SqlDbType.Decimal).Value=x.CreditLimit;c.Parameters.Add("@U",SqlDbType.BigInt).Value=u;}
 static CustomerDto Read(SqlDataReader r)=>new(r.GetInt64(0),$"CUS-{r.GetInt64(0):0000}",r.GetString(1),r.GetString(2),r.IsDBNull(3)?"":r.GetString(3),r.IsDBNull(4)?"":r.GetString(4),r.IsDBNull(5)?"":r.GetString(5),r.IsDBNull(6)?"":r.GetString(6),r.GetDecimal(7),r.GetDecimal(8),r.GetBoolean(9),DateTime.SpecifyKind(r.GetDateTime(10),DateTimeKind.Utc),Convert.ToBase64String((byte[])r[11]));
}

