import { useState } from 'react'
import Icon from '../../components/Icon'
import { usePharmacyData } from '../../hooks/usePharmacyData'
import { money } from './pageUtils'
import { Badge, Button, DataTable, PageHeader, Panel, SearchBox } from './shared'

export function Reports({ showToast }) {
  const { data: { reportRows, salesTrend, purchases, medicines } } = usePharmacyData()
  const totalSales = reportRows.reduce((sum, row) => sum + row.sales, 0)
  const totalPurchases = purchases.reduce((sum, row) => sum + row.total, 0)
  const grossProfit = reportRows.reduce((sum, row) => sum + row.profit, 0)
  const stockValue = medicines.reduce((sum, item) => sum + item.stock * item.purchase, 0)
  return (
    <><PageHeader title="Reports" description="Review sales, purchases, inventory and profitability."><Button variant="secondary" icon="download" onClick={() => showToast('Excel report exported')}>Export Excel</Button><Button variant="secondary" icon="download" onClick={() => showToast('PDF report exported')}>Export PDF</Button></PageHeader>
      <Panel title="Report filters" className="filter-panel"><div className="report-filters"><label>From<input type="date" defaultValue="2026-09-01"/></label><label>To<input type="date" defaultValue="2026-09-12"/></label><label>Report type<select><option>Sales vs purchase</option><option>Stock valuation</option><option>Expiry report</option><option>Gross profit</option></select></label><Button onClick={() => showToast('Report filters applied')}>Apply filters</Button></div></Panel>
      <div className="report-stats"><div><span>Total sales</span><b>{money(totalSales)}</b><small className="positive">API calculated</small></div><div><span>Total purchases</span><b>{money(totalPurchases)}</b><small>API transactions</small></div><div><span>Gross profit</span><b>{money(grossProfit)}</b><small className="positive">Calculated margin</small></div><div><span>Stock value</span><b>{money(stockValue)}</b><small>At purchase price</small></div></div>
      <div className="reports-grid"><Panel title="Sales vs purchases"><div className="bar-chart">{salesTrend.slice(0,12).map((value,index) => <div key={index}><i style={{height:`${value}%`}}></i><em style={{height:`${value*.65}%`}}></em></div>)}</div><div className="chart-legend"><span><i></i>Sales</span><span><i></i>Purchases</span></div></Panel><Panel title="Top-selling medicines"><DataTable headers={['Medicine','Units','Sales','Profit']}>{reportRows.map((row) => <tr key={row.name}><td><b>{row.name}</b></td><td>{row.sold}</td><td>{money(row.sales)}</td><td><b className="positive">{money(row.profit)}</b></td></tr>)}</DataTable></Panel></div>
    </>
  )
}
export function Schemes({ showToast }) {
  const { data: { schemes: rows } } = usePharmacyData()
  const [adding, setAdding] = useState(false)
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState('All status')
  const [editing, setEditing] = useState(null)
  const visible = rows.filter(row => row.join(' ').toLowerCase().includes(search.toLowerCase()) && (status === 'All status' || row[5] === status))
  return <><PageHeader title="Schemes & Discounts" description="Configure item offers, bill discounts and stock-clearance schemes."><Button icon="plus" onClick={() => { setEditing(null); setAdding(!adding) }}>New scheme</Button></PageHeader>{(adding || editing) && <Panel title={editing ? 'Edit scheme' : 'Create scheme'} className="inline-form-panel"><form className="scheme-form" onSubmit={(e)=>{e.preventDefault();setAdding(false);setEditing(null);showToast(editing ? 'Scheme updated successfully' : 'Scheme created successfully')}}><label>Scheme name<input required defaultValue={editing?.[1]} placeholder="Offer name"/></label><label>Scheme type<select defaultValue={editing?.[3]}><option>Quantity scheme</option><option>Item discount</option><option>Bill discount</option><option>Clearance</option></select></label><label>Value<input required placeholder="e.g. 5%"/></label><label>Valid until<input type="date"/></label><Button type="submit">Save scheme</Button></form></Panel>}<div className="mini-stats customer-stats"><div><Icon name="receipt"/><span>Active schemes<b>{rows.filter(row => row[5] === 'Active').length}</b></span></div><div><Icon name="cart"/><span>Configured offers<b>{rows.length}</b></span></div><div><Icon name="chart"/><span>API status<b>Live</b></span></div></div><Panel title="Scheme register"><div className="toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search schemes..."/><select value={status} onChange={(e) => setStatus(e.target.value)}><option>All status</option><option>Active</option><option>Draft</option></select></div><DataTable headers={['Code','Scheme','Applies to','Type','Validity','Status','']}>{visible.map(row=><tr key={row[0]}><td><b className="primary-text">{row[0]}</b></td><td><b>{row[1]}</b></td><td>{row[2]}</td><td>{row[3]}</td><td>{row[4]}</td><td><Badge tone={row[5]==='Active'?'success':'neutral'}>{row[5]}</Badge></td><td><button className="icon-button" aria-label={`Edit ${row[1]}`} onClick={() => { setAdding(false); setEditing(row) }}><Icon name="edit" size={16}/></button></td></tr>)}</DataTable></Panel></>
}
export function Accounts({ showToast }) {
  const { data: { ledger, salesTrend } } = usePharmacyData()
  const [entry, setEntry] = useState('')
  return <><PageHeader title="Accounts" description="Track cash, bank, expenses and party outstanding balances."><Button variant="secondary" icon="plus" onClick={() => setEntry(entry === 'expense' ? '' : 'expense')}>Add expense</Button><Button icon="plus" onClick={() => setEntry(entry === 'voucher' ? '' : 'voucher')}>Receipt / Payment</Button></PageHeader>{entry && <Panel title={entry === 'expense' ? 'Record expense' : 'Record receipt / payment'} className="inline-form-panel"><form className="workflow-form" onSubmit={(e) => { e.preventDefault(); setEntry(''); showToast(entry === 'expense' ? 'Expense recorded' : 'Account voucher recorded') }}><label>{entry === 'expense' ? 'Expense head' : 'Voucher type'}{entry === 'expense' ? <select><option>Electricity</option><option>Rent</option><option>Staff expense</option><option>Other</option></select> : <select><option>Receipt</option><option>Payment</option></select>}</label><label>Account / party<input required placeholder="Account or party name"/></label><label>Payment mode<select><option>Cash</option><option>Bank</option><option>UPI</option></select></label><label>Amount<input required min="1" type="number" placeholder="₹ 0"/></label><label>Reference<input placeholder="Optional reference"/></label><Button type="submit" icon="check">Save voucher</Button></form></Panel>}<div className="report-stats"><div><span>Cash entries</span><b>{ledger.filter(row => row[3] === 'Cash').length}</b><small>From API</small></div><div><span>Total vouchers</span><b>{ledger.length}</b><small>Current register</small></div><div><span>Receipts</span><b>{ledger.filter(row => row[6] === 'Credit').length}</b><small>Credit entries</small></div><div><span>Payments</span><b>{ledger.filter(row => row[6] === 'Debit').length}</b><small>Debit entries</small></div></div><div className="reports-grid"><Panel title="Cash flow"><div className="bar-chart accounts-chart">{salesTrend.slice(0,12).map((v,i)=><div key={i}><i style={{height:`${v}%`}}></i><em style={{height:`${v*.55}%`}}></em></div>)}</div><div className="chart-legend"><span><i></i>Income</span><span><i></i>Expense</span></div></Panel><Panel title="Outstanding summary"><div className="outstanding-list">{ledger.slice(0,3).map(row => <div key={row[0]}><span>{row[2]}<small>{row[1]} · {row[4]}</small></span><b>{money(row[5])}</b></div>)}</div></Panel></div><Panel title="Recent ledger entries" className="account-ledger"><DataTable headers={['Voucher','Type','Account / Party','Mode','Date','Amount','Entry']}>{ledger.map(row=><tr key={row[0]}><td><b className="primary-text">{row[0]}</b></td><td>{row[1]}</td><td><b>{row[2]}</b></td><td>{row[3]}</td><td>{row[4]}</td><td><b>{money(row[5])}</b></td><td><Badge tone={row[6]==='Credit'?'success':'warning'}>{row[6]}</Badge></td></tr>)}</DataTable></Panel></>
}
export function Compliance({ showToast }) {
  const { data: { filings } } = usePharmacyData()
  const [detail, setDetail] = useState('')
  return <><PageHeader title="GST & Compliance" description="Monitor GST summaries, e-invoices and filing readiness."><Button variant="secondary" icon="download" onClick={() => showToast('GST data exported for September 2026')}>Export GST data</Button><Button icon="check" onClick={() => showToast('Validation complete — no tax mismatch found')}>Validate entries</Button></PageHeader><div className="compliance-banner"><span><Icon name="check" size={22}/></span><div><b>Books are GST-ready</b><p>All transactions through 12 Sep 2026 are validated. No tax mismatch detected.</p></div><Badge tone="success">Healthy</Badge></div><div className="report-stats"><div><span>Taxable sales</span><b>₹4,12,450</b><small>September 2026</small></div><div><span>Output GST</span><b>₹32,180</b><small>Collected</small></div><div><span>Input GST</span><b>₹24,620</b><small>Available credit</small></div><div><span>Net payable</span><b>₹7,560</b><small>Due 20 Sep</small></div></div>{detail && <Panel title={`${detail} details`} className="inline-form-panel" action={<button className="text-button" onClick={() => setDetail('')}>Close</button>}><div className="detail-summary"><div><span>Validated records</span><b>126</b></div><div><span>Taxable value</span><b>₹4,12,450</b></div><div><span>Tax difference</span><b className="positive">₹0</b></div><div><span>Readiness</span><Badge tone="success">Ready</Badge></div></div></Panel>}<Panel title="Compliance overview"><DataTable headers={['Return / Service','Description','Period','Due / Usage','Status','Action']}>{filings.map(row=><tr key={row[0]}><td><b>{row[0]}</b></td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td><td><Badge tone={row[4]==='Due soon'?'warning':'success'}>{row[4]}</Badge></td><td><button className="text-button" onClick={() => setDetail(row[0])}>View details</button></td></tr>)}</DataTable></Panel></>
}
